name: Build Release

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Release channel'
        required: true
        type: choice
        default: production
        options:
          - production
          - beta

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, sqlite
          tools: composer, npm

      - name: Determine release version
        id: version
        run: php scripts/bump-version.php "${{ github.event.inputs.channel }}"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress --no-dev --optimize-autoloader

      - name: Build assets
        run: | 
          npm install
          npm run build
          
          mkdir public/build/img
          cp public/images/flags.png public/build/img/
          cp public/images/flags@2x.png public/build/img/

      - name: Create Release Build
        run: |
          # Remove unnecessary files
          rm -rf .git .github tests
          rm -f .gitattributes .gitignore phpunit.xml

          # Create zip file
          zip -r eventschedule.zip .

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: ${{ steps.version.outputs.prerelease == 'true' }}
          title: "${{ steps.version.outputs.channel == 'beta' && 'Beta Release' || 'Latest Release' }}"
          automatic_release_tag: "${{ steps.version.outputs.version }}"
          files: |
            eventschedule.zip
